core/urls.py
from django.urls import path
from core.views import index, category_list_view,  category_product_list__view, product_list_view, vendor_list_view, vendor_detail_view, product_detail_view, tag_list, ajax_add_review, search_view, filter_product, add_to_cart, cart_view, delete_item_from_cart, update_cart, checkout_view, payment_completed_view, contact, ajax_contact_form, wishlist_view, add_to_wishlist, customer_dashboard, order_detail, make_address_default, checkout

app_name = "core"

urlpatterns = [

    # Home page
    path("", index, name='index'),
    path("products/", product_list_view, name='product-list'),
    path("product/<pid>/", product_detail_view, name='product-detail'),

    # Category
    path("category/", category_list_view, name='category-list'),
    path("category/<cid>/", category_product_list__view, name='category-product-list'),

    # Vendor
    path("vendors/", vendor_list_view, name="vendor-list"),
    path("vendor/<vid>/", vendor_detail_view, name="vendor-detail"),

    # Tags
    path("products/tag/<slug:tag_slug>/", tag_list, name="tags"),

    # Add reviews
    path("ajax-add-review/<pid>", ajax_add_review, name="ajax-add-review"),

    # Serach
    path("search/", search_view, name="search"),


    # Filter Product url
    path("filter-products/", filter_product, name="filter-product"),

     # Add to cart URL
    path("add-to-cart/", add_to_cart, name="add-to-cart"),

    # Cart Page URL
    path("cart/", cart_view, name="cart"),

    # Delete ITem from Cart
    path("delete-from-cart/", delete_item_from_cart, name="delete-from-cart"),

    # Update  Cart
    path("update-cart/", update_cart, name="update-cart"),

    # Checkout  URL
    path("checkout/", checkout_view, name="checkout"),

    path('checkout-items/', checkout, name='checkout-items'),

    # Payment Successful
    path("payment-completed/", payment_completed_view, name="payment-completed"),


    # Dahboard URL
    path("dashboard/", customer_dashboard, name="dashboard"),

    # Order Detail URL
    path("dashboard/order/<int:id>", order_detail, name="order-detail"),

    # Making address defauly
    path("make-default-address/", make_address_default, name="make-default-address"),

    # wishlist page
    path("wishlist/", wishlist_view, name="wishlist"),

    # adding to wishlist
    path("add-to-wishlist/", add_to_wishlist, name="add-to-wishlist"),

    path("contact/", contact, name="contact"),

    path("ajax-contact-form/", ajax_contact_form, name="ajax-contact-form"),


]

ecomprj/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls")),
    path("user/", include("userauths.urls")),

    path("ckeditor/", include("ckeditor_uploader.urls")), # for image uploading in blog
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/forms.py
from django import forms
from core.models import ProductReview


class ProductReviewForm(forms.ModelForm):
    review = forms.CharField(widget=forms.Textarea(attrs={'placeholder': "Write review"}))

    class Meta:
        model = ProductReview
        fields = ['review', 'rating']

core/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import JsonResponse
from django.db.models import Count, Avg
from core.models import CartOrderProducts, Product, Category, Vendor, CartOrder, ProductImages, ProductReview, wishlist_model, Address
from userauths.models import ContactUs
from taggit.models import Tag
from core.forms import ProductReviewForm
from django.template.loader import  render_to_string
from django.contrib import messages

from django.urls import reverse
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt

from django.contrib.auth.decorators import login_required

def index(request):
    #products = Product.objects.all().order_by("-id")
    products = Product.objects.filter(product_status="published", featured=True)
    context = {
        "products": products,
    }
    return render(request, 'core/index.html', context)


def product_list_view(request):
    products = Product.objects.filter(product_status="published")

    context = {
        "products":products,
    }

    return render(request, 'core/product-list.html', context)


def category_list_view(request):
    categories = Category.objects.all()
    context = {
        "categories":categories
    }
    return render(request, 'core/category-list.html', context)

def category_product_list__view(request, cid):

    category = Category.objects.get(cid=cid) 
    products = Product.objects.filter(product_status="published", category=category)

    context = {
        "category":category,
        "products":products,
    }
    return render(request, "core/category-product-list.html", context)

def vendor_list_view(request):
    vendors = Vendor.objects.all()
    context = {
        "vendors": vendors,
    }
    return render(request, "core/vendor-list.html", context)

def vendor_detail_view(request, vid):
    vendor = Vendor.objects.get(vid=vid)
    products = Product.objects.filter(vendor=vendor, product_status="published")

    context = {
        "vendor": vendor,
        "products": products,
    }
    return render(request, "core/vendor-detail.html", context)

def product_detail_view(request, pid):
    product = Product.objects.get(pid=pid)
    #product = get_object_or_404(Product, pid=pid)
    products = Product.objects.filter(category=product.category).exclude(pid=pid)

    # Getting all the review
    reviews = ProductReview.objects.filter(product=product).order_by("-date")

    # Getting average review
    average_rating = ProductReview.objects.filter(product=product).aggregate(rating=Avg('rating'))

     # Product Review form
    review_form = ProductReviewForm()

    make_review = True 

    if request.user.is_authenticated:
        user_review_count = ProductReview.objects.filter(user=request.user, product=product).count()

        if user_review_count > 0:
            make_review = False
    
    # Get related products images
    p_image = product.p_images.all()

    context = {
        "p": product,
        "p_image": p_image,
        "average_rating": average_rating,
        "review_form": review_form,
        "make_review":  make_review,
        "products": products,
        "reviews": reviews,
        
    }

    return render(request, "core/product-detail.html", context)

def tag_list(request, tag_slug=None):

    products = Product.objects.filter(product_status="published").order_by("-id")

    tag = None 
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        products = products.filter(tags__in=[tag])

    context = {
        "products": products,
        "tag": tag
    }

    return render(request, "core/tag.html", context)

def ajax_add_review(request, pid):
    product = Product.objects.get(pk=pid)
    user = request.user 

    review = ProductReview.objects.create(
        user=user,
        product=product,
        review = request.POST['review'],
        rating = request.POST['rating'],
    )

    context = {
        'user': user.username,
        'review': request.POST['review'],
        'rating': request.POST['rating'],
    }

    average_reviews = ProductReview.objects.filter(product=product).aggregate(rating=Avg("rating"))

    return JsonResponse(
       {
         'bool': True,
        'context': context,
        'average_reviews': average_reviews
       }
    )

def search_view(request):
    query = request.GET.get("q")

    products = Product.objects.filter(title__icontains=query).order_by("-date")

    context = {
        "products": products,
        "query": query,
    }
    return render(request, "core/search.html", context)

def filter_product(request):
    categories = request.GET.getlist("category[]")
    vendors = request.GET.getlist("vendor[]")


    products = Product.objects.filter(product_status="published").order_by("-id").distinct()


    if len(categories) > 0:
        products = products.filter(category__id__in=categories).distinct() 
        
    if len(vendors) > 0:
        products = products.filter(vendor__id__in=vendors).distinct() 

    data = render_to_string("core/async/product-list.html", {"products": products})
    return JsonResponse({"data": data})

def add_to_cart(request):
    cart_product = {}

    if 'id' in request.GET and 'title' in request.GET and 'qty' in request.GET and 'price' in request.GET:
        cart_product[str(request.GET['id'])] = {
            'title': request.GET['title'],
            'qty': request.GET['qty'],
            'price': request.GET['price'],
            'image': request.GET.get('image', None),
            'pid': request.GET.get('pid', None),
        }

        if 'cart_data_obj' in request.session:
            if str(request.GET['id']) in request.session['cart_data_obj']:
                cart_data = request.session['cart_data_obj']
                cart_data[str(request.GET['id'])]['qty'] = int(cart_product[str(request.GET['id'])]['qty'])
                cart_data.update(cart_data)
                request.session['cart_data_obj'] = cart_data
            else:
                cart_data = request.session['cart_data_obj']
                cart_data.update(cart_product)
                request.session['cart_data_obj'] = cart_data
        else:
            request.session['cart_data_obj'] = cart_product

        return JsonResponse({"data": request.session['cart_data_obj'], 'totalcartitems': len(request.session['cart_data_obj'])})
    else:
        return JsonResponse({"error": "Missing required parameters"})
    
def cart_view(request):
    cart_total_amount = 0
    if 'cart_data_obj' in request.session:
        for p_id, item in request.session['cart_data_obj'].items():
            cart_total_amount += int(item['qty']) * float(item['price'])
        return render(request, "core/cart.html", {"cart_data":request.session['cart_data_obj'], 'totalcartitems': len(request.session['cart_data_obj']), 'cart_total_amount':cart_total_amount})
    else:
        messages.warning(request, "Your cart is empty")
        return redirect("core:index")
    
def delete_item_from_cart(request):
    product_id = str(request.GET['id'])
    if 'cart_data_obj' in request.session:
        if product_id in request.session['cart_data_obj']:
            cart_data = request.session['cart_data_obj']
            del request.session['cart_data_obj'][product_id]
            request.session['cart_data_obj'] = cart_data
    
    cart_total_amount = 0
    if 'cart_data_obj' in request.session:
        for p_id, item in request.session['cart_data_obj'].items():
            cart_total_amount += int(item['qty']) * float(item['price'])

    context = render_to_string("core/async/cart-list.html", {"cart_data":request.session['cart_data_obj'], 'totalcartitems': len(request.session['cart_data_obj']), 'cart_total_amount':cart_total_amount})
    return JsonResponse({"data": context, 'totalcartitems': len(request.session['cart_data_obj'])})

def update_cart(request):
    product_id = str(request.GET['id'])
    product_qty = request.GET['qty']

    if 'cart_data_obj' in request.session:
        if product_id in request.session['cart_data_obj']:
            cart_data = request.session['cart_data_obj']
            cart_data[str(request.GET['id'])]['qty']=product_qty
            request.session['cart_data_obj'] = cart_data
    
    cart_total_amount = 0
    if 'cart_data_obj' in request.session:
        for p_id, item in request.session['cart_data_obj'].items():
            cart_total_amount += int(item['qty']) * float(item['price'])

    context = render_to_string("core/async/cart-list.html", {"cart_data":request.session['cart_data_obj'], 'totalcartitems': len(request.session['cart_data_obj']), 'cart_total_amount':cart_total_amount})
    return JsonResponse({"data": context, 'totalcartitems': len(request.session['cart_data_obj'])})

def checkout_view(request):

    cart_total_amount = 0
    cart_data = request.session.get('cart_data_obj', {})
    
    for p_id, item in cart_data.items():
        cart_total_amount += int(item['qty']) * float(item['price'])

    try:
        active_address = Address.objects.get(user=request.user, status=True)
    except:
        messages.warning(request, "There are multiple addresses, only one should be activated.")
        active_address = None
    
    return render(request, "core/checkout.html", {
        "cart_data": cart_data,
        "totalcartitems": len(cart_data),
        "cart_total_amount": cart_total_amount,
        "active_address":active_address
    })

def checkout(request):
    # Get cart data from session
    cart_data = request.session.get('cart_data_obj', {})
    
    # Calculate total price and update inventory
    total_price = 0
    for product_id, item in cart_data.items():
        # Calculate total price for the item
        total_price += float(item['price']) * int(item['qty'])

    # Create a CartOrder instance
    order = CartOrder.objects.create(
        user=request.user,  # Assuming user is authenticated
        price=total_price
    )

templates/core/category-list.html
{% extends "partials/base.html" %}
{% load static %}
{% block content %}


    <main class="main">
        <div class="page-header mt-30 mb-75">
            <div class="container">
                <div class="archive-header">
                    <div class="row align-items-center">
                        <div class="col-xl-3">
                            <h1 class="mb-15">Categories</h1>
                            <div class="breadcrumb">
                                <a href="index.html" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                                <span></span> Categories
                            </div>
                        </div>
                       
                    </div>
                </div>
            </div>
        </div>
        <div class="page-content mb-50">
            <div class="container">
                <div class="row">
                    <div class="col-lg-9">
                        <div class="shop-product-fillter mb-50 pr-30">
                            <div class="totall-product">
                                <h2>
                                    <img class="w-36px mr-10" src="assets/imgs/theme/icons/category-1.svg" alt="" />
                                    {{categories.count}} Categories
                                </h2>
                            </div>
                            <div class="sort-by-product-area">
                                <div class="sort-by-cover mr-10">
                                    <div class="sort-by-product-wrap">
                                        <div class="sort-by">
                                            <span><i class="fi-rs-apps"></i>Show:</span>
                                        </div>
                                        <div class="sort-by-dropdown-wrap">
                                            <span> 50 <i class="fi-rs-angle-small-down"></i></span>
                                        </div>
                                    </div>
                                    <div class="sort-by-dropdown">
                                        <ul>
                                            <li><a class="active" href="#">50</a></li>
                                            <li><a href="#">100</a></li>
                                            <li><a href="#">150</a></li>
                                            <li><a href="#">200</a></li>
                                            <li><a href="#">All</a></li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="sort-by-cover">
                                    <div class="sort-by-product-wrap">
                                        <div class="sort-by">
                                            <span><i class="fi-rs-apps-sort"></i>Sort:</span>
                                        </div>
                                        <div class="sort-by-dropdown-wrap">
                                            <span>Featured <i class="fi-rs-angle-small-down"></i></span>
                                        </div>
                                    </div>
                                    <div class="sort-by-dropdown">
                                        <ul>
                                            <li><a class="active" href="#">Featured</a></li>
                                            <li><a href="#">Newest</a></li>
                                            <li><a href="#">Most comments</a></li>
                                            <li><a href="#">Release Date</a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="loop-grid pr-30">
                            <div class="row">
                                {% for c in categories %}
                                <article class="col-xl-4 col-lg-6 col-md-6 text-center hover-up mb-30 animated">
                                    <div class="post-thumb">
                                        <a href="{% url 'core:category-product-list' c.cid %}">
                                            <img class="border-radius-15" src="{{c.image.url}}" alt="" />
                                        </a>
                                        <div class="entry-meta">
                                            <a class="entry-meta meta-2" href="{% url 'core:wishlist' %}"><i class="fi-rs-heart"></i></a>
                                        </div>
                                    </div>
                                    <div class="entry-content-2">
                                        <!-- <h6 class="mb-10 font-sm"><a class="entry-meta text-muted" href="blog-category-grid.html">Side Dish</a></h6> -->
                                        <h4 class="post-title mb-15">
                                            <a href="{% url 'core:category-product-list' c.cid %}">{{ c.title }}</a>
                                        </h4>
                                        <div class="entry-meta font-xs color-grey mt-10 pb-10">
                                            <div>
                                                <span class="hit-count mr-10">{{c.category.count}} Product{{c.category.count|pluralize}}</span>
                                            </div>
                                        </div>
                                    </div>
                                </article>
                                {% endfor %}
                                
                            </div>
                        </div>
                        <div class="pagination-area mt-15 mb-sm-5 mb-lg-0">
                            <nav aria-label="Page navigation example">
                                <ul class="pagination justify-content-start">
                                    <li class="page-item">
                                        <a class="page-link" href="#"><i class="fi-rs-arrow-small-left"></i></a>
                                    </li>
                                    <li class="page-item"><a class="page-link" href="#">1</a></li>
                                    <li class="page-item active"><a class="page-link" href="#">2</a></li>
                                    <li class="page-item"><a class="page-link" href="#">3</a></li>
                                    <li class="page-item"><a class="page-link dot" href="#">...</a></li>
                                    <li class="page-item"><a class="page-link" href="#">6</a></li>
                                    <li class="page-item">
                                        <a class="page-link" href="#"><i class="fi-rs-arrow-small-right"></i></a>
                                    </li>
                                </ul>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>

{% endblock content %} 

    

templates/core/checkout.html
{% extends "partials/base.html" %}
{% load static %}
{% block content %}
    <main class="main">
        <div class="page-header breadcrumb-wrap">
            <div class="container">
                <div class="breadcrumb">
                    <a href="index.html" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                    <span></span> Shop
                    <span></span> Checkout
                </div>
            </div>
        </div>
        <div class="container mb-80 mt-50">
            <div class="row">
                <div class="col-lg-8 mb-40">
                    <h1 class="heading-2 mb-10">Checkout</h1>
                    <div class="d-flex justify-content-between">
                        <h6 class="text-body">There are <span class="text-brand">{{ totalcartitems }}</span> products in your cart</h6>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-7">
                    
                    <div class="row">
                        <h4 class="mb-30">Billing Details</h4>
                        <form method="post">
                            <div class="row">
                                <div class="form-group col-lg-6">
                                    <input type="text" required="" name="fname" value="{{ request.user.username|title }}" placeholder="First name *">
                                </div>
                                <div class="form-group col-lg-6">
                                    <input type="text" required="" name="lname" placeholder="mobile" value="{{ active_address.mobile }}">
                                </div>
                            </div>
                            <div class="row">
                                <div class="form-group col-lg-6">
                                    <input type="text" name="billing_address" value="{{ active_address.address }}" required="" placeholder="Address *">
                                </div>
                                
                            </div>

                        </form>
                    </div>
                </div>
                <div class="col-lg-5">
                    <div class="border p-40 cart-totals ml-30 mb-50">
                        <div class="d-flex align-items-end justify-content-between mb-30">
                            <h4>Your Order</h4>
                            <h6 class="text-muted">Subtotal - <span class="text-brand">Rs{{cart_total_amount|floatformat:2}}</span></h6>

                        </div>
                        <div class="divider-2 mb-30"></div>
                        <a href="{% url 'core:cart' %}" class="btn btn-fill-out btn-block mt-30 mb-40">Go back to Cart</a>
                        
                        <div class="table-responsive order_table checkout">
                            <table class="table no-border">
                                <tbody>
                                    {% for product_id, item in cart_data.items %}
                                        <tr>
                                            <td class="image product-thumbnail"><img src="{{ item.image }}" alt="#"></td>
                                            <td>
                                                <h6 class="w-160 mb-5"><a href="{% url 'core:product-detail' item.pid %}" class="text-heading">{{ item.title }}</a></h6></span>
                                            </td>
                                            <td>
                                                <h6 class="text-muted pl-20 pr-20">x {{ item.qty }}</h6>
                                            </td>
                                            <td>
                                                <h5 class="text-muted">Rs {{ item.price }}</h5>
                                            </td>
                                            <td>
                                                <h5 class="text-brand">Rs{% widthratio item.price 1 item.qty %}</h5>
                                            </td>
                                        </tr>
                                    {% endfor %}

                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="payment ml-30">
                        <h4 class="mb-30">Payment</h4>
                        <div class="payment_option">
                            
                            <div class="custome-radio">
                                <input class="form-check-input" required="" type="radio" name="payment_option" id="exampleRadios4" checked="">
                                <label class="form-check-label" for="exampleRadios4" data-bs-toggle="collapse" data-target="#checkPayment" aria-controls="checkPayment">Cash on delivery</label>
                            </div>
                           
                        </div>
                        <div class="payment-logo d-flex">
                            <img class="mr-15" src="{% static 'assets/imgs/theme/icons/payment-paypal.svg' %}" alt="">
                            <img class="mr-15" src="{% static 'assets/imgs/theme/icons/payment-visa.svg' %}" alt="">
                            <img class="mr-15" src="{% static 'assets/imgs/theme/icons/payment-master.svg' %}" alt="">
                            <img src="{% static 'assets/imgs/theme/icons/payment-zapper.svg' %}" alt="">
                        </div>
                        <a href="#" class="btn btn-fill-out btn-block mt-30 checkout-btn" id="checkout-btn">Place an Order<i class="fi-rs-sign-out ml-15"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock content %}

templates/core/wishlist.html
{% extends "partials/base.html" %}
{% load static %}
{% block content %}
    <main class="main">
        <div class="page-header breadcrumb-wrap">
            <div class="container">
                <div class="breadcrumb">
                    <a href="index.html" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                    <span></span> Shop <span></span> Fillter
                </div>
            </div>
        </div>
        <div class="container mb-30 mt-50">
            <div class="row">
                <div class="col-xl-10 col-lg-12 m-auto">
                    <div class="mb-50">
                        <h1 class="heading-2 mb-10">Your Wishlist</h1>
                        <h6 class="text-body">There are <span class="text-brand">5</span> products in this list</h6>
                    </div>
                    <div class="table-responsive shopping-summery">
                        <table class="table table-wishlist">
                            <thead>
                                <tr class="main-heading">
                                    <th class="custome-checkbox start pl-30">
                                        <input class="form-check-input" type="checkbox" name="checkbox" id="exampleCheckbox11" value="" />
                                        <label class="form-check-label" for="exampleCheckbox11"></label>
                                    </th>
                                    <th scope="col" colspan="2">Product</th>
                                    <th scope="col">Price</th>
                                    <th scope="col">Stock Status</th>
                                    <th scope="col">Action</th>
                                    <th scope="col" class="end">Remove</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for w in w %}
                                {{w}}

                                <tr class="pt-30">
                                    <td class="custome-checkbox pl-30">
                                        <input class="form-check-input" type="checkbox" name="checkbox" id="exampleCheckbox1" value="" />
                                        <label class="form-check-label" for="exampleCheckbox1"></label>
                                    </td>
                                    <td class="image product-thumbnail pt-40"><img src="{{w.product.image.url}}" alt="#" /></td>
                                    <td class="product-des product-name">
                                        {% if w.product.pid %}
                                            <h6><a class="product-name mb-10" href="{% url "core:product-detail" w.product.pid %}">{{ w.product.title|truncatechars:30 }}</a></h6>
                                        {% else %}
                                            <h6>{{ w.product.title|truncatechars:30 }}</h6>
                                        {% endif %}

                                        
                                    </td>
                                    <td class="price d-fdlex fs-1" data-title="Price">
                                        <span class="text-brand">Rs</span><span class="text-brand current-product-price-{{ w.product.id }}">{{ w.product.price }}</span>
                                    </td>
                                    <td class="text-center detail-info" data-title="Stock">
                                        <span class="stock-status in-stock mb-0"> {% if w.product_in_stock %} In Stock {% else %} Out of stock {% endif %} </span>
                                    </td>
                                    <td class="text-right" data-title="Cart">
                                        <input type="hidden" value="1" id="product-quantity" class="product-quantity-{{ w.product.id }}">
                                        <input type="hidden" class="product-pid-{{ w.product.id }}" value="{{ w.product.pid }}">"
                                        <input type="hidden" class="product-image-{{ w.product.id }}" value="{{ w.product.image.url }}">
                                        <input type="hidden" class="product-id-{{ w.product.id }}" value="{{ w.product.id }}">
                                        <input type="hidden" class="product-title-{{ w.product.id }}" value="{{ w.product.title }}">
                                        <button class="btn btn-sm add-to-cart-btn" data-index="{{ w.product.id }}">Add to cart</button>
                                    </td>
                                    <td class="action text-center" data-title="Remove">
                                        <a href="#" class="text-body"><i class="fi-rs-trash"></i></a>
                                    </td>
                                </tr>
                                {% empty %}
                                <tr>
                                    <td><p>Nothing in wishlist</p></td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock content %}
    